version: 2
registries:
  takumi_guard_pypi:
    type: python-index
    url: https://pypi.flatt.tech/simple/
    token: ${{secrets.TAKUMI_GUARD_TOKEN}}

updates:
  - package-ecosystem: "pip"
    directory: "/"
    registries:
      - takumi_guard_pypi
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - package-ecosystem: "pip"
    directory: "/chapter4"
    registries:
      - takumi_guard_pypi
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - package-ecosystem: "pip"
    directory: "/chapter5"
    registries:
      - takumi_guard_pypi
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - package-ecosystem: "pip"
    directory: "/chapter6"
    registries:
      - takumi_guard_pypi
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - package-ecosystem: "pip"
    directory: "/chapter7"
    registries:
      - takumi_guard_pypi
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
